# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'binary_search_QWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QSize
from PyQt5.QtGui import QIcon, QPixmap

import binary_search


class Ui_Form(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setObjectName("Form")
        self.resize(715, 488)
        self.setStyleSheet("background-color:#FC3962;")
        self.create_array_QlineEdit = QtWidgets.QLineEdit(self)
        self.create_array_QlineEdit.setGeometry(QtCore.QRect(86, 210, 301, 31))
        self.create_array_QlineEdit.setObjectName("create_array_QlineEdit")
        self.create_array_QlineEdit.setStyleSheet("color: #FC3962; background-color: white; font: 7pt; font: bold;")
        self.show_array_QTextbrowser = QtWidgets.QTextBrowser(self)
        self.show_array_QTextbrowser.setGeometry(QtCore.QRect(40, 20, 641, 71))
        self.show_array_QTextbrowser.setObjectName("show_array_QTextbrowser")
        self.show_array_QTextbrowser.setStyleSheet("color: #FC3962; background-color: white; font: 7pt; font: bold;")
        self.create_array_QpushButton = QtWidgets.QPushButton(self)
        self.create_array_QpushButton.setGeometry(QtCore.QRect(200, 260, 81, 31))
        self.create_array_QpushButton.setObjectName("create_array_QpushButton")
        self.create_array_QpushButton.setStyleSheet("color: #FC3962; background-color: white; font: 7pt; font: bold;")
        self.find_number_QLabel = QtWidgets.QLabel(self)
        self.find_number_QLabel.setGeometry(QtCore.QRect(465, 180, 71, 21))
        self.find_number_QLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.find_number_QLabel.setObjectName("find_number_QLabel")
        self.find_number_QLabel.setStyleSheet("color: white; background-color: #FC3962; font: 7pt; font: bold;")
        self.find_number_QPushbutton = QtWidgets.QPushButton(self)
        self.find_number_QPushbutton.setGeometry(QtCore.QRect(460, 260, 81, 31))
        self.find_number_QPushbutton.setObjectName("find_number_QPushbutton")
        self.find_number_QPushbutton.setStyleSheet("color: #FC3962; background-color: white; font: 7pt; font: bold;")
        self.find_number_QLineEdit = QtWidgets.QLineEdit(self)
        self.find_number_QLineEdit.setGeometry(QtCore.QRect(442, 210, 121, 31))
        self.find_number_QLineEdit.setObjectName("find_number_QLineEdit")
        self.find_number_QLineEdit.setStyleSheet("color: #FC3962; background-color: white; font: 7pt; font: bold;")
        self.create_array_QLabel = QtWidgets.QLabel(self)
        self.create_array_QLabel.setGeometry(QtCore.QRect(190, 180, 91, 21))
        self.create_array_QLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.create_array_QLabel.setObjectName("create_array_QLabel")
        self.create_array_QLabel.setStyleSheet("color: white; background-color: #FC3962; font: 7pt; font: bold;")
        self.number_order_QLabel = QtWidgets.QLabel(self)
        self.number_order_QLabel.setGeometry(QtCore.QRect(580, 215, 91, 21))
        self.number_order_QLabel.setText("")
        self.number_order_QLabel.setObjectName("number_order_QLabel")
        self.number_order_QLabel.setStyleSheet("color: white; background-color: #FC3962; font: 16pt; font: bold;")
        self.find_number_information_QLabel = QtWidgets.QLabel(self)
        self.find_number_information_QLabel.setGeometry(QtCore.QRect(430, 290, 151, 31))
        self.find_number_information_QLabel.setText("")
        self.find_number_information_QLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.find_number_information_QLabel.setObjectName("number_order_information_QLabel")
        self.find_number_information_QLabel.setStyleSheet("color: white; background-color: #FC3962; font: 7pt; font: bold;")
        self.create_array_information_Qlabel = QtWidgets.QLabel(self)
        self.create_array_information_Qlabel.setGeometry(QtCore.QRect(165, 290, 176, 30))
        self.create_array_information_Qlabel.setText("")
        self.create_array_information_Qlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.create_array_information_Qlabel.setObjectName("create_array_information_Qlabel")
        self.create_array_information_Qlabel.setStyleSheet("color: white; background-color: #FC3962; font: 7pt; font: bold;")
        self.pixmap = QPixmap("back_icon.png")
        self.backButton = QtWidgets.QPushButton(self)
        self.backButton.setGeometry(QtCore.QRect(0, 5, 30, 23))
        self.backButton.setObjectName("backButton")
        self.backButton.setIcon(QIcon(self.pixmap))
        self.backButton.setIconSize(QSize(30,23))

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)
        self.global_list=[]

        self.create_array_QpushButton.clicked.connect(self.create_array)
        self.find_number_QPushbutton.clicked.connect(self.find_number)
    def find_number(self):
        self.number_order_QLabel.setText("")
        if(len(self.global_list)==0):
            self.find_number_information_QLabel.setText("Please create array.")
        else:
            number = self.integer_controller(self.find_number_QLineEdit.text())
            if(number != None):


                index = binary_search.binarySearch(self.global_list,0,len(self.global_list)-1,number)
                if (index==-1):
                    self.find_number_information_QLabel.setText("There isn't this number\nin the list.")
                else:
                    self.find_number_information_QLabel.setText("")
                    self.number_order_QLabel.setText(str(index)+". index")
            else:
                self.find_number_information_QLabel.setText("Please enter integer number.")
    def integer_controller(self,number):
        try:
            number=int(number)
            return number
        except:
            self.find_number_information_QLabel.setText("Please enter integer number.")

    def create_array(self):
        list = self.arrayStringToInteger(self.create_array_QlineEdit.text().split(","))
        if (list != False):
            self.controller = self.list_controller(list)
            if (self.controller == False):
                self.create_array_information_Qlabel.setText("Each number must be entered once.")
            else:
                list.sort()
                self.global_list = list
                self.create_array_information_Qlabel.setText("")
                self.show_array_QTextbrowser.setText(str(list))


    def arrayStringToInteger(self,list):
        for i in range(len(list)):
            try:
                list[i] = int(list[i])
            except:
                self.create_array_information_Qlabel.setText("Please enter integer numbers.\nPut comma(,) between numbers.")
                return False
        return list

    def list_controller(self,list):
        for i in list:
            if ((list.count(i)==0) or (list.count(i)==1)):
                return True
            else:
                return False

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.create_array_QpushButton.setText(_translate("Form", "Create Array"))
        self.find_number_QLabel.setText(_translate("Form", "Find number"))
        self.find_number_QPushbutton.setText(_translate("Form", "Find"))
        self.create_array_QLabel.setText(_translate("Form", "Create Array"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = Ui_Form()
    ui.show()
    sys.exit(app.exec_())
