# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mail.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt5 import QtCore, QtGui, QtWidgets
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setObjectName("MainWindow")
        self.resize(880, 786)
        self.setStyleSheet("background:#FC3962;")
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(90, 20, 651, 491))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.email_QLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.email_QLabel.setStyleSheet("color:white; font-size:16px;")
        self.email_QLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.email_QLabel.setObjectName("email_QLabel")
        self.verticalLayout.addWidget(self.email_QLabel)
        self.phoneQLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.phoneQLabel.setStyleSheet("color:white; font-size:16px;")
        self.phoneQLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.phoneQLabel.setObjectName("phoneQLabel")
        self.verticalLayout.addWidget(self.phoneQLabel)
        self.texbodytBrowser = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.texbodytBrowser.setStyleSheet("background-color:white;")
        self.texbodytBrowser.setObjectName("texbodytBrowser")
        self.verticalLayout.addWidget(self.texbodytBrowser)
        self.sendQpushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.sendQpushButton.setStyleSheet("QPushButton\n"
"{\n"
"    color: #fc3962;\n"
"    background-color:#FAF3F5;\n"
"    border-color: #1e1e1e;\n"
"    border-style: solid;\n"
"    border-radius: 6;\n"
"    padding: 3px;\n"
"    font-size: 12px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    min-width: 40px;\n"
"}")
        self.sendQpushButton.setObjectName("senQpushButton")
        self.verticalLayout.addWidget(self.sendQpushButton)
        self.informationQLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.informationQLabel.setStyleSheet("color:white;")
        self.informationQLabel.setText("")
        self.informationQLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.informationQLabel.setObjectName("informationQLabel")
        self.verticalLayout.addWidget(self.informationQLabel)
        self.qrCodeQLabelinfo = QtWidgets.QLabel(self.centralwidget)
        self.qrCodeQLabelinfo.setGeometry(QtCore.QRect(160, 530, 171, 21))
        self.qrCodeQLabelinfo.setStyleSheet("color:white; font-size:16px;")
        self.qrCodeQLabelinfo.setAlignment(QtCore.Qt.AlignCenter)
        self.qrCodeQLabelinfo.setObjectName("qrCodeQLabelinfo")
        self.qrcCodeQLabelimage = QtWidgets.QLabel(self.centralwidget)
        self.qrcCodeQLabelimage.setGeometry(QtCore.QRect(140, 560, 201, 181))
        self.qrcCodeQLabelimage.setText("")
        self.path=os.getcwd()
        self.path=self.path.replace("\\", "/",)
        self.qrcCodeQLabelimage.setPixmap(QtGui.QPixmap(self.path+"/information QRCODE.png"))
        self.qrcCodeQLabelimage.setObjectName("qrcCodeQLabelimage")
        self.qrCodeQLabelinfo_2 = QtWidgets.QLabel(self.centralwidget)
        self.qrCodeQLabelinfo_2.setGeometry(QtCore.QRect(450, 530, 171, 21))
        self.qrCodeQLabelinfo_2.setStyleSheet("color:white; font-size:16px;")
        self.qrCodeQLabelinfo_2.setAlignment(QtCore.Qt.AlignCenter)
        self.qrCodeQLabelinfo_2.setObjectName("qrCodeQLabelinfo_2")
        self.qrcCodeQLabelimage_2 = QtWidgets.QLabel(self.centralwidget)
        self.qrcCodeQLabelimage_2.setGeometry(QtCore.QRect(430, 560, 201, 191))
        self.qrcCodeQLabelimage_2.setText("")
        self.qrcCodeQLabelimage_2.setPixmap(QtGui.QPixmap(self.path+"/İkçü QRCODE.png"))
        self.qrcCodeQLabelimage_2.setObjectName("qrcCodeQLabelimage_2")
        self.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.backButton = QtWidgets.QPushButton(self)
        self.backButton.setGeometry(QtCore.QRect(0, 5, 30, 23))
        self.backButton.setStyleSheet("background-color:#ffffff; color:#FC3962;")
        self.backButton.setObjectName("backButton")
        self.backButton.setText("Back")
        self.retranslateUi(self)
        self.sendQpushButton.clicked.connect(self.Sendit)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.email_QLabel.setText(_translate("MainWindow", "E-MAIL: batuhan-498@hotmail.com"))
        self.phoneQLabel.setText(_translate("MainWindow", "Phone: 05435504483"))
        self.sendQpushButton.setText(_translate("MainWindow", "Send"))
        self.qrCodeQLabelinfo.setText(_translate("MainWindow", "You can contact me "))
        self.qrCodeQLabelinfo_2.setText(_translate("MainWindow", "Izmir Katip Çelebi Web"))
    def Sendit(self):

        try:
            appmessage = str(self.texbodytBrowser.toPlainText())
            def send_mail(text="text", subject='My Subject', from_email="My Name <YOURMAILADDRESS>", to_email=None,
                          html=None):
                assert isinstance(to_email, list)
                message = MIMEMultipart('alternative')
                message["From"] = from_email
                message["To"] = ", ".join(to_email)
                message["Subject"] = subject

                body = MIMEText(text, 'plain')
                message.attach(body)

                if html is not None:
                    my_html = MIMEText(html, 'html')
                    message.attach(my_html)


                message = message.as_string()

                server = smtplib.SMTP(host='smtp.gmail.com', port=587)
                server.ehlo()
                server.starttls()
                server.login("mermercalismasi2020@gmail.com","mermer2020calismasi")
                server.sendmail(from_email, to_email, message)
                server.quit()

            send_mail(text=appmessage, subject='Message',
                      to_email=['mermercalismasi2020@gmail.com','batuhan-498@hotmail.com'])
            self.informationQLabel.setText("Mail send successfully.")
        except:

            self.informationQLabel.setText("Gmail Service Unavailable")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = Ui_MainWindow()
    ui.show()
    sys.exit(app.exec_())
