# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import random
from timeit import default_timer

import WEB_PYQT
import binary
import mailQWidget
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QPixmap, QPalette
from matplotlib import pyplot as plt

import BucketSort
import CountingSort
import HeapSort
import QuickSort
import RadixSort

import matrixProduct_QWidget
import binary_search_QWidget
import fibonacci_QWidget
import sortingWidget
from SortingAlgorithms import InsertionSort, MergeSort, BubbleSort


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(401, 494)

        MainWindow.setStyleSheet("background-color: #FC3962;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-5, -30, 741, 521))
        self.tabWidget.setObjectName("tabWidget")
        self.menu_QWidget = QtWidgets.QWidget()
        self.menu_QWidget.setObjectName("menu_QWidget")
        self.katip_image_QLabel = QtWidgets.QLabel(self.menu_QWidget)
        self.katip_image_QLabel.setGeometry(QtCore.QRect(100, 110, 200, 100))
        self.katip_image_QLabel.setText("")
        self.katip_image_QLabel.setObjectName("katip_image_QLabel")
        # adding image to label
        self.pixmap = QPixmap('katip.png')
        self.katip_image_QLabel.setPixmap(self.pixmap)
        self.mail_QPushbutton = QtWidgets.QPushButton(self.menu_QWidget)
        self.mail_QPushbutton.setGeometry(QtCore.QRect(315, 5, 90, 31))
        self.mail_QPushbutton.setObjectName("fibonacci_QPushbutton")
        self.mail_QPushbutton.setStyleSheet("color: #FC3962; background-color: white; font: 8pt; font: bold;")
        self.binary_QPushbutton = QtWidgets.QPushButton(self.menu_QWidget)
        self.binary_QPushbutton.setGeometry(QtCore.QRect(210, 320, 155, 41))
        self.binary_QPushbutton.setObjectName("binary_QPushbutton")
        self.binary_QPushbutton.setStyleSheet("color: #FC3962; background-color: white; font: 8pt; font: bold;")
        self.fibonacci_QPushbutton = QtWidgets.QPushButton(self.menu_QWidget)
        self.fibonacci_QPushbutton.setGeometry(QtCore.QRect(40, 320, 155, 41))
        self.fibonacci_QPushbutton.setObjectName("fibonacci_QPushbutton")
        self.fibonacci_QPushbutton.setStyleSheet("color: #FC3962; background-color: white; font: 8pt; font: bold;")
        self.comparison_QPushbutton = QtWidgets.QPushButton(self.menu_QWidget)
        self.comparison_QPushbutton.setGeometry(QtCore.QRect(210, 260, 155, 41))
        self.comparison_QPushbutton.setObjectName("comparison_QPushbutton")
        self.comparison_QPushbutton.setStyleSheet("color: #FC3962; background-color: white; font: 7pt; font: bold;")
        self.webBrowser_QPushbutton = QtWidgets.QPushButton(self.menu_QWidget)
        self.webBrowser_QPushbutton.setGeometry(QtCore.QRect(210, 380, 155, 41))
        self.webBrowser_QPushbutton.setObjectName("comparison_QPushbutton")
        self.webBrowser_QPushbutton.setStyleSheet("color: #FC3962; background-color: white; font: 9pt; font: bold;")
        self.sorting_QPushbutton = QtWidgets.QPushButton(self.menu_QWidget)
        self.sorting_QPushbutton.setGeometry(QtCore.QRect(40, 260, 155, 41))
        self.sorting_QPushbutton.setObjectName("sorting_QPushbutton")
        self.sorting_QPushbutton.setStyleSheet("color: #FC3962; background-color: white; font: 8pt; font: bold;")
        self.matrix_product_QPushbutton = QtWidgets.QPushButton(self.menu_QWidget)
        self.matrix_product_QPushbutton.setGeometry(QtCore.QRect(40, 380, 155, 41))
        self.matrix_product_QPushbutton.setObjectName("pushButton")
        self.matrix_product_QPushbutton.setStyleSheet("color: #FC3962; background-color: white; font: 8pt; font: bold;")
        self.name_surname_QLabel = QtWidgets.QLabel(self.menu_QWidget)
        self.name_surname_QLabel.setGeometry(QtCore.QRect(80, 60, 250, 31))
        self.name_surname_QLabel.setTextFormat(QtCore.Qt.AutoText)
        self.name_surname_QLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.name_surname_QLabel.setWordWrap(False)
        self.name_surname_QLabel.setObjectName("name_surname_QLabel")
        self.name_surname_QLabel.setStyleSheet("color: white; font: 13pt; font: bold;")
        self.tabWidget.addTab(self.menu_QWidget, "")
        self.sorting_QWidget = sortingWidget.Ui_MainWindow()
        self.sorting_QWidget.setObjectName("sorting_QWidget")
        self.tabWidget.addTab(self.sorting_QWidget, "")

        self.fibonacci_QWidget = fibonacci_QWidget.Ui_FiboBinary()
        self.fibonacci_QWidget.setObjectName("fibonacci_QWidget")
        self.tabWidget.addTab(self.fibonacci_QWidget, "")

        self.binary_search_QWidget = binary.Ui_FiboBinary()
        self.binary_search_QWidget.setObjectName("binary_search_QWidget")
        self.tabWidget.addTab(self.binary_search_QWidget, "")

        self.matrix_product_QWidget = matrixProduct_QWidget.Ui_Form()
        self.matrix_product_QWidget.setObjectName("matrix_product_QWidget")
        self.tabWidget.addTab(self.matrix_product_QWidget, "")

        self.mail_QWidget = mailQWidget.Ui_MainWindow()
        self.mail_QWidget.setObjectName("mail_QWidget")
        self.tabWidget.addTab(self.mail_QWidget, "")

        self.webBrowser_QWidget = WEB_PYQT.Window()
        self.webBrowser_QWidget.setObjectName("Browser_QWidget")
        self.tabWidget.addTab(self.webBrowser_QWidget, "")



        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.sorting_QPushbutton.clicked.connect(lambda:self.main_interface(1))
        self.comparison_QPushbutton.clicked.connect(self.graph)
        self.fibonacci_QPushbutton.clicked.connect(lambda:self.main_interface(2))
        self.binary_QPushbutton.clicked.connect(lambda:self.main_interface(3))
        self.matrix_product_QPushbutton.clicked.connect(lambda:self.main_interface(4))
        self.mail_QPushbutton.clicked.connect(lambda:self.main_interface(5))
        self.webBrowser_QPushbutton.clicked.connect(lambda:self.main_interface(6))


        self.sorting_QWidget.backButton.clicked.connect(lambda:self.main_interface(0))
        self.fibonacci_QWidget.backButton.clicked.connect(lambda:self.main_interface(0))
        self.binary_search_QWidget.backButton.clicked.connect(lambda:self.main_interface(0))
        self.matrix_product_QWidget.backButton.clicked.connect(lambda:self.main_interface(0))
        self.mail_QWidget.backButton.clicked.connect(lambda:self.main_interface(0))
        self.webBrowser_QWidget.SearchButton.clicked.connect(lambda:self.main_interface(0))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def main_interface(self,index):
        if (index==0):
            MainWindow.setWindowTitle(QtCore.QCoreApplication.translate("MainWindow", "Batuhan Beel"))
            MainWindow.resize(401, 494)
            MainWindow.setFixedHeight(494)
            MainWindow.setFixedWidth(401)
            self.tabWidget.setGeometry(QtCore.QRect(-5, -30, 741, 521))
            self.tabWidget.setCurrentIndex(index)
        elif(index==1):
            MainWindow.setWindowTitle(QtCore.QCoreApplication.translate("MainWindow", "Sorting Algorithms"))
            MainWindow.resize(755, 830)
            MainWindow.setFixedHeight(830)
            MainWindow.setFixedWidth(755)
            self.tabWidget.setCurrentIndex(index)
            self.tabWidget.setGeometry(QtCore.QRect(-5, -30, 765, 852))
        elif(index==2):
            MainWindow.setWindowTitle(QtCore.QCoreApplication.translate("MainWindow", "Fibonacci"))
            MainWindow.resize(985, 515)
            MainWindow.setFixedHeight(515)
            MainWindow.setFixedWidth(985)
            self.tabWidget.setCurrentIndex(index)
            self.tabWidget.setGeometry(QtCore.QRect(-5, -30, 1000, 530))
        elif(index==3):
            MainWindow.setWindowTitle(QtCore.QCoreApplication.translate("MainWindow", "Binary Search"))
            self.tabWidget.setCurrentIndex(index)
            MainWindow.resize(715, 560)
            MainWindow.setFixedHeight(560)
            MainWindow.setFixedWidth(715)

            self.tabWidget.setGeometry(QtCore.QRect(-5, -30, 730, 590))
            self.tabWidget.setStyleSheet('background-color: #FC3962;')
        elif(index==4):
            MainWindow.setWindowTitle(QtCore.QCoreApplication.translate("MainWindow", "Matrix Product"))
            MainWindow.resize(1060, 700)
            MainWindow.setFixedHeight(700)
            MainWindow.setFixedWidth(1060)
            self.tabWidget.setCurrentIndex(index)
            self.tabWidget.setGeometry(QtCore.QRect(-5, -30, 1070, 800))
        elif(index==5):
            MainWindow.setWindowTitle(QtCore.QCoreApplication.translate("MainWindow", "Contact"))
            MainWindow.resize(850, 800)
            MainWindow.setFixedHeight(800)
            MainWindow.setFixedWidth(850)
            self.tabWidget.setCurrentIndex(index)
            self.tabWidget.setGeometry(QtCore.QRect(-5, -30, 860, 840))
        elif(index==6):
            MainWindow.setWindowTitle(QtCore.QCoreApplication.translate("MainWindow", "Katip Browser"))
            MainWindow.resize(850, 790)
            MainWindow.setFixedHeight(790)
            MainWindow.setFixedWidth(850)
            self.tabWidget.setCurrentIndex(index)
            self.tabWidget.setGeometry(QtCore.QRect(-5, -30, 860, 840))

        else:
            self.tabWidget.setStyleSheet('background-color: #FC3962;')


    def graph(self):
        list = [100,250,500,1000,2000,3000]
        sortingList=[InsertionSort.insertionSort, MergeSort.mergeSort, BubbleSort.bubbleSort,HeapSort.heapSort,QuickSort.quick_sort,CountingSort.counting_sort,RadixSort.radixSort,BucketSort.bucket_sort]
        insertion_sorting_time_List =[]
        merge_sorting_time_List =[]
        bubble_sorting_time_List =[]
        heap_sorting_time_List =[]
        quick_sorting_time_List =[]
        counting_sorting_time_List =[]
        radix_sorting_time_List =[]
        bucket_sorting_time_List =[]
        for i in range(len(list)):
            random_list=[]
            for j in range(list[i]):
                random_list.append(random.randint(0,1000))
            for k in range(len(sortingList)):

                temporaryList = []
                temporaryList.extend(random_list)
                start = default_timer()
                if (k==4):
                    temporaryList=sortingList[k](temporaryList,0,len(temporaryList)-1)
                elif(k==5):
                    temporaryList=sortingList[k](temporaryList,min(temporaryList),max(temporaryList))

                else:
                    temporaryList=sortingList[k](temporaryList)


                end = default_timer()
                result = round((end-start),5)


                if(k==0):
                    insertion_sorting_time_List.append(result)
                elif(k==1):
                    merge_sorting_time_List.append(result)
                elif(k==2):
                    bubble_sorting_time_List.append(result)
                elif(k==3):
                    heap_sorting_time_List.append(result)
                elif(k==4):
                    quick_sorting_time_List.append(result)
                elif(k==5):
                    counting_sorting_time_List.append(result)
                elif(k==6):
                    radix_sorting_time_List.append(result)
                elif(k==7):
                    bucket_sorting_time_List.append(result)


        insertion_sort_y = insertion_sorting_time_List
        plt.plot(list, insertion_sort_y, label = "Insertion Sort")

        merge_sort_y = merge_sorting_time_List
        plt.plot(list, merge_sort_y, label = "Merge Sort")

        bubble_sort_y = bubble_sorting_time_List
        plt.plot(list, bubble_sort_y, label = "Bubble Sort")

        heap_sort_y = heap_sorting_time_List
        plt.plot(list, heap_sort_y, label = "Heap Sort")

        quick_sort_y = quick_sorting_time_List
        plt.plot(list, quick_sort_y, label = "Quick Sort")

        counting_sort_y = counting_sorting_time_List
        plt.plot(list, counting_sort_y, label = "Counting Sort")

        radix_sort_y = radix_sorting_time_List
        plt.plot(list, radix_sort_y, label = "Radix Sort")

        bucket_sort_y = bucket_sorting_time_List
        plt.plot(list, bucket_sort_y, label = "Bucket Sort")



        # naming the x axis
        plt.xlabel('Array Size')
        # naming the y axis
        plt.ylabel('Time (s)')
        # giving a title to my graph
        plt.title('Sorting Comparison')
        # show a legend on the plot
        plt.legend()
        # function to show the plot
        plt.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Batuhan Beel 180403031"))
        self.mail_QPushbutton.setText(_translate("MainWindow", "Contact"))
        self.binary_QPushbutton.setText(_translate("MainWindow", "BINARY SEARCH"))
        self.fibonacci_QPushbutton.setText(_translate("MainWindow", "FIBONACCI"))
        self.comparison_QPushbutton.setText(_translate("MainWindow", "COMPARISON SORTING TIME"))
        self.webBrowser_QPushbutton.setText(_translate("MainWindow", "Web Browser"))
        self.sorting_QPushbutton.setText(_translate("MainWindow", "SORTING"))
        self.name_surname_QLabel.setText(_translate("MainWindow", "BATUHAN BEEL 180403031"))
        self.matrix_product_QPushbutton.setText(_translate("MainWindow", "MATRIX PRODUCT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.menu_QWidget), _translate("MainWindow", "menu_QWidget"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sorting_QWidget), _translate("MainWindow", "sorting_QWidget"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fibonacci_QWidget), _translate("MainWindow", "fibonacci_QWidget"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
