# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QFont


class Ui_Form(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setObjectName("Form")
        self.resize(300, 500)
        self.studentLabel = QtWidgets.QLabel(self)
        self.studentLabel.setGeometry(QtCore.QRect(10, 20, 271, 31))
        self.studentLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.studentLabel.setObjectName("studentLabel")
        self.studentLabel.setFont(QFont("Arial",15))
        self.imageQLabel = QtWidgets.QLabel(self)
        self.imageQLabel.setGeometry(QtCore.QRect(20, 90, 250, 200))
        self.imageQLabel.setText("")
        self.imageQLabel.setObjectName("imageQLabel")
        self.sortingButton = QtWidgets.QPushButton(self)
        self.sortingButton.setGeometry(QtCore.QRect(20, 300, 251, 31))
        self.sortingButton.setObjectName("sortingButton")
        self.comparisonSortingButton = QtWidgets.QPushButton(self)
        self.comparisonSortingButton.setGeometry(QtCore.QRect(20, 340, 251, 31))
        self.comparisonSortingButton.setObjectName("comparisonSortingButton")
        self.exitButton = QtWidgets.QPushButton(self)
        self.exitButton.setGeometry(QtCore.QRect(20, 380, 251, 31))
        self.exitButton.setObjectName("exitButton")
        self.exitButton.clicked.connect(self.aa)

        self.pixmap = QPixmap('katip.png')

        # adding image to label
        self.imageQLabel.setPixmap(self.pixmap)

        self.retranslateUi()
        self.buttonsLabels()
        QtCore.QMetaObject.connectSlotsByName(self)
    def aa(self):
        print("hayda")
    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.studentLabel.setText(_translate("Form", "BATUHAN BEEL 180403031"))
        self.sortingButton.setText(_translate("Form", "SORTING ALGORITHMS"))
        self.comparisonSortingButton.setText(_translate("Form", "COMPARISON OF THE SORTING ALGORITHMS"))
        self.exitButton.setText(_translate("Form", "EXIT"))

    def buttonsLabels(self):
        pass







if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = Ui_Form()
    Form.show()
    sys.exit(app.exec_())
